[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel@1.12.3
    bblanchon/ArduinoJson@6.21.5
    tzapu/WiFiManager@2.0.17
    aircoookie/Espalexa@2.7.0
